[package]
name = "roller"
version = "0.1.0"
authors = ["User"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.3"
